name: Static Analysis

on:
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install pylint 
        pip install -r requirements.txt

    - name: Run Pylint and generate report
      run: |
        find suprb/ -name "*.py" -print0 | xargs -0 -n 1 -P 4 pylint --max-line-length=120 --output-format=text > pylint-report.txt || true

    - name: Check for warnings in Pylint report
      id: lint-check
      run: |
          if grep -q "rated at" pylint-report.txt; then
            if grep -q "Your code has been rated at 10.00/10" pylint-report.txt; then
              echo "status=success" >> $GITHUB_ENV
              echo "No warnings or errors found."
            else
              echo "status=warning" >> $GITHUB_ENV
              echo "Linting passed with warnings. Review the report."
            fi
          else
            echo "status=failure" >> $GITHUB_ENV
            echo "No linting output found. Please check the configuration."
            exit 1
          fi
      
    - name: Output Pylint status
      run: echo "Pylint Status: ${{ env.status }}"

    - name: Upload pylint report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint-report.txt
